In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [14]:
csv_file_US_videos= "Resources/USvideos.csv"
USvideos = pd.read_csv(csv_file_US_videos)
USvideos.columns

US_videos_cleaned=USvideos[['video_id', 'trending_date','title','category_id','channel_title','publish_time','views', 'likes', 'dislikes', 'comment_count','description']]
US_videos_cleaned.head()

,video_id,trending_date,title,category_id,channel_title,publish_time,views,likes,dislikes,comment_count,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,22,CaseyNeistat,2017-11-13T17:13:01.000Z,748374,57527,2966,15954,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,24,LastWeekTonight,2017-11-13T07:30:00.000Z,2418783,97185,6146,12703,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",23,Rudy Mancuso,2017-11-12T19:05:24.000Z,3191434,146033,5339,8181,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,24,Good Mythical Morning,2017-11-13T11:00:04.000Z,343168,10172,666,2146,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,24,nigahiga,2017-11-12T18:01:41.000Z,2095731,132235,1989,17518,I know it's been a while since we did this sho...

In [19]:
json_file = "Resources/US_category_id.json"
US_category_id = pd.read_json(json_file)

Item_id=US_category_id["items"]
new_Item_id=pd.json_normalize(Item_id)
Categories=new_Item_id [['id', 'snippet.title']]
Categories.rename(columns={"id": "CategoryID", "snippet.title": "CategoryName"}, inplace = True)

Categories


# category=new_Item_id('id','snippet.title')

/Users/yuanzhong/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

   CategoryID           CategoryName
0           1       Film & Animation
1           2       Autos & Vehicles
2          10                  Music
3          15         Pets & Animals
4          17                 Sports
5          18           Short Movies
6          19        Travel & Events
7          20                 Gaming
8          21          Videoblogging
9          22         People & Blogs
10         23                 Comedy
11         24          Entertainment
12         25        News & Politics
13         26          Howto & Style
14         27              Education
15         28   Science & Technology
16         29  Nonprofits & Activism
17         30                 Movies
18         31        Anime/Animation
19         32       Action/Adventure
20         33               Classics
21         34                 Comedy
22         35            Documentary
23         36                  Drama
24         37                 Family
25         38                Foreign
26         39                 Horror
27         40         Sci-Fi/Fantasy
28         41               Thriller
29         42                 Shorts
30         43                  Shows
31         44               Trailers